import { getLibros , getZapatillas} from './communicationManager.js'

export default {
    data() {
      return {
        message: 'Hello Vue!',
        divActual: 'portada',
        libros: [],
        zapatillas: [],
        comandaActual:{
            preuTotal: 0,
            productes: []
        }
      }
      },
      methods: {
        cambiarDiv(id) {
          this.divActual=id;
        },
        mostrar(id) {
          return (this.divActual==id);
        },
        afegir(id){
          this.comandaActual.productes.push(id);
        }
      },
     created(){
         getLibros().then(libros => {
          this.libros = libros;   
      })
  
      getZapatillas().then(z => {
        this.zapatillas = z;   
    })
  },
  template: `
  <div>
  <div v-if="mostrar('portada')">
        <!-- Jumbotron -->
      <div class="jumbotron jumbotron-fluid">
          <div class="container text-center">
              <h1 class="display-4">Las  zapatillas deportivas al mejor precio</h1>
              <p class="lead">Encuentra las zapatillas que se adaptan a tu estilo y a tu deporte favorito.</p>
              <a class="btn btn-primary btn-lg"  @click="cambiarDiv('tienda')" href="#" role="button">Ver catálogo</a>
          </div>
      </div>
  </div>
  <div v-if="mostrar('tienda')">
      <h1>Tienda</h1>           
      <button class="btn btn-primary"  @click="cambiarDiv('portada')">Volver a portada</button>
      <button  class="btn btn-primary"  @click="cambiarDiv('checkout')">Finalitzar comanda</button>

      <div class="row">
          <div class="col-md-8">
            <div class="row">
                  <div class="col-md-3" v-for="(actual,index) in zapatillas">                              
                          <!-- Cards -->              
                          <div class="card mb-4 shadow-sm">
                              <!-- Image generated by graphic_art(prompt = "una imagen de zapatillas deportivas de color rojo") -->
                              <img src = "zapatillas-rojas.png" alt = "Zapatillas rojas" class = "card-img-top"> 
                              <div class = "card-body">
                                  <h5 class = "card-title">{{actual.nombre}}</h5>
                                  <p class = "card-text">  {{actual.descripcion}}</p>
                                  <p class = "card-text"><strong>{{actual.precio}}    </strong></p>
                                  <button class="btn btn-primary" @click="afegir(index)">+</button>
                                  <button class="btn btn-primary" @click="eliminar(index)">-</button>
                          </div>
                          </div>                       
                    </div>
                  </div>
              </div>

          <div class="col-md-4">
             <h2>Resum de la compra</h2> 
              <ul>
                   <li v-for="actual in comandaActual.productes">
                        {{zapatillas[actual].nombre}} - {{zapatillas[actual].precio}}
                   </li>
              </ul>

          </div>
      </div>   
  </div>
  <div v-if="mostrar('checkout')">
      <h1>Resum comanda</h1>    
      <button class="btn btn-primary" @click="cambiarDiv('tienda')">Tornar a la botiga</button>
      Aqui nos conectamos al LocalStorage para saber si sabemos el usuario 
      y si no lo sabemos lo pedimos
  </div>
</div>`}